package bf.memoire;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.view.*;import android.widget.*;import android.net.Uri;import java.io.*;import java.util.*;
public class AnnotationActivity extends Activity {
    Drawing drawing;
    protected void onCreate(Bundle state){super.onCreate(state);String id=getIntent().getStringExtra("fileId");if(id==null||!id.matches("[a-fA-F0-9-]{36}")){finish();return;}String path=new File(getFilesDir(),"attachments/"+id).toString();BitmapFactory.Options options=new BitmapFactory.Options();options.inJustDecodeBounds=true;BitmapFactory.decodeFile(path,options);options.inSampleSize=1;while(Math.max(options.outWidth,options.outHeight)/options.inSampleSize>1600)options.inSampleSize*=2;options.inJustDecodeBounds=false;Bitmap bitmap=BitmapFactory.decodeFile(path,options);if(bitmap==null){Toast.makeText(this,"Ce fichier n’est pas une image lisible.",1).show();finish();return;}LinearLayout root=new LinearLayout(this);root.setOrientation(1);TextView label=new TextView(this);label.setText("Annoter une copie de l’image");label.setTextSize(20);label.setPadding(24,24,24,24);root.addView(label);drawing=new Drawing(bitmap);root.addView(drawing,new LinearLayout.LayoutParams(-1,0,1));LinearLayout actions=new LinearLayout(this);root.addView(actions);action(actions,"Annuler",()->finish());action(actions,"Effacer",()->{drawing.paths.clear();drawing.invalidate();});action(actions,"Conserver",()->save());setContentView(root);}
    void action(LinearLayout row,String name,Runnable run){Button b=new Button(this);b.setText(name);b.setAllCaps(false);row.addView(b,new LinearLayout.LayoutParams(0,-2,1));b.setOnClickListener(v->run.run());}
    void save(){try{Bitmap result=drawing.bitmap.copy(Bitmap.Config.ARGB_8888,true);Canvas canvas=new Canvas(result);for(Path path:drawing.paths)canvas.drawPath(path,drawing.paint);String id=UUID.randomUUID().toString();File file=new File(getFilesDir(),"attachments/"+id);try(OutputStream out=new FileOutputStream(file)){if(!result.compress(Bitmap.CompressFormat.PNG,100,out))throw new IOException();}result.recycle();Uri uri=new Uri.Builder().scheme("content").authority("bf.memoire.files").appendPath(id).appendPath("Image-annotee.png").build();setResult(RESULT_OK,new Intent().setData(uri));finish();}catch(Exception e){Toast.makeText(this,"Impossible de conserver l’image.",1).show();}}
    class Drawing extends View {
        Bitmap bitmap;Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);List<Path> paths=new ArrayList<>();float scale=1,left=0,top=0;Path current;
        Drawing(Bitmap value){super(AnnotationActivity.this);bitmap=value;paint.setColor(Color.rgb(218,72,67));paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(6);paint.setStrokeCap(Paint.Cap.ROUND);paint.setStrokeJoin(Paint.Join.ROUND);setBackgroundColor(Color.rgb(235,239,236));}
        protected void onDraw(Canvas canvas){super.onDraw(canvas);scale=Math.min(getWidth()/(float)bitmap.getWidth(),getHeight()/(float)bitmap.getHeight());left=(getWidth()-bitmap.getWidth()*scale)/2;top=(getHeight()-bitmap.getHeight()*scale)/2;canvas.save();canvas.translate(left,top);canvas.scale(scale,scale);canvas.drawBitmap(bitmap,0,0,null);for(Path path:paths)canvas.drawPath(path,paint);canvas.restore();}
        public boolean onTouchEvent(android.view.MotionEvent event){float x=(event.getX()-left)/scale,y=(event.getY()-top)/scale;if(event.getAction()==MotionEvent.ACTION_DOWN){current=new Path();current.moveTo(x,y);paths.add(current);return true;}if(event.getAction()==MotionEvent.ACTION_MOVE&&current!=null){current.lineTo(x,y);invalidate();return true;}if(event.getAction()==MotionEvent.ACTION_UP){performClick();return true;}return true;}
        public boolean performClick(){super.performClick();return true;}
    }
}
