package bf.memoire;

import android.app.*;
import android.os.*;
import android.content.*;
import android.net.Uri;
import android.database.Cursor;
import android.provider.OpenableColumns;
import android.view.*;
import android.widget.*;
import android.text.*;
import org.json.*;
import java.io.*;
import java.util.*;
import java.util.zip.*;

public class MainActivity extends Activity {
    LocalStore store;
    JSONObject db;
    String currentSpace="Études", projectFilter="", statusFilter="";
    boolean globalSearch=false, inbox=false, archive=false;
    final Map<String,EditText> blockEditors=new LinkedHashMap<>();
    int fontSize=16;
    char[] archivePassword=null;boolean pendingExportEncrypted=false,unlocked=false,credentialPending=false;
    boolean mergeImport=false;String restoreScope="";
    JSONObject pendingMedia;
    int mediaRequest=0;

    JSONArray notes;
    LinearLayout page, list;
    JSONObject editing;
    EditText title, body, tags;
    final Map<String,EditText> fields = new LinkedHashMap<>();
    boolean trash=false;
    String query="";
    String filter="";
    long afterDate=0;boolean onlyFavorites=false;
    String replacingFile="";
    final Handler handler=new Handler();
    final Runnable autosave=()->saveEditor();
    File state;
    static final int ATTACH=1, EXPORT=2, IMPORT=3;
    @Override public void onCreate(Bundle b) {
        super.onCreate(b);
        state=new File(getFilesDir(),"memory.json");
        store=new LocalStore(this);
        try {db=store.load();if(db==null)db=new JSONObject(read(new android.util.AtomicFile(state).openRead()));}
        catch(FileNotFoundException e) { db=new JSONObject(); put(db,"schema",1); put(db,"notes",new JSONArray()); }
        catch(Exception e) {layout("Mémoire — récupération nécessaire");TextView error=new TextView(this);error.setText("Les données locales ne peuvent pas être lues. Elles ont été conservées sans modification. Ferme l’application et demande une récupération avant de poursuivre.");page.addView(error);return;}
        notes=db.optJSONArray("notes");
        if(notes==null) { notes=new JSONArray(); put(db,"notes",notes); }
        if(db.optJSONArray("templates")==null)put(db,"templates",new JSONArray());
        if(db.optJSONArray("spaces")==null)put(db,"spaces",new JSONArray(Arrays.asList("Études","Travail","Personnel","Projets")));
        seedTemplates();
        fontSize=db.optInt("fontSize",16);currentSpace=db.optString("lastSpace","Études");
        for(int i=0;i<notes.length();i++){JSONObject n=notes.optJSONObject(i);if(!n.has("space"))put(n,"space","Études");if(!n.has("blocks"))put(n,"blocks",new JSONArray());}
        try{store.save(db);if(state.exists())state.delete();new File(state.toString()+".bak").delete();}catch(Exception e){layout("Migration interrompue");page.addView(text("Les données d’origine ont été conservées. La migration ne peut pas être terminée : "+e.getMessage(),16,ink()));return;}home();
        unlocked=!db.optBoolean("appLock")||(b!=null&&b.getBoolean("unlocked"));
        if(b!=null){screen=b.getString("screen","Accueil");query=b.getString("query","");pendingBlockType=b.getString("pendingBlockType","");replacingFile=b.getString("replace","");pendingExportEncrypted=b.getBoolean("encryptedExport");home();try{String media=b.getString("media");if(media!=null)pendingMedia=new JSONObject(media);}catch(Exception ignored){}String editId=b.getString("editId");if(editId!=null)for(int i=0;i<notes.length();i++){JSONObject n=notes.optJSONObject(i);if(n.optString("id").equals(editId)){edit(n);break;}}}
        String openId=getIntent().getStringExtra("openNote");if(openId!=null)for(int j=0;j<notes.length();j++){JSONObject n=notes.optJSONObject(j);if(n.optString("id").equals(openId)){edit(n);break;}}
        if(b==null&&Intent.ACTION_SEND.equals(getIntent().getAction())) {
            create();
            CharSequence text=getIntent().getCharSequenceExtra(Intent.EXTRA_TEXT);
            if(text!=null) body.setText(text);
            Uri uri=getIntent().getParcelableExtra(Intent.EXTRA_STREAM);
            if(uri!=null) attach(uri);
        }
        if(db.optBoolean("appLock")&&!unlocked)unlock();
    }
    static void put(JSONObject o,String k,Object v) { try { o.put(k,v); } catch(JSONException e) { throw new IllegalStateException(e); } }
    static void copy(InputStream in,OutputStream out)throws IOException {byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);}
    static String read(InputStream in)throws IOException { try(InputStream s=in; ByteArrayOutputStream out=new ByteArrayOutputStream()) { copy(s,out); return out.toString("UTF-8"); } }
    void persist() {
        try {if(store!=null)store.save(db);}catch(Exception e){message("Échec de l’enregistrement : "+e.getMessage());}
    }
    void unlock(){
        android.app.KeyguardManager manager=(android.app.KeyguardManager)getSystemService(KEYGUARD_SERVICE);
        if(!manager.isDeviceSecure()){put(db,"appLock",false);persist();message("Configure d’abord le verrouillage Android.");return;}
        unlocked=false;getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE,WindowManager.LayoutParams.FLAG_SECURE);page.setVisibility(View.INVISIBLE);
        if(Build.VERSION.SDK_INT>=28){android.hardware.biometrics.BiometricPrompt prompt=new android.hardware.biometrics.BiometricPrompt.Builder(this).setTitle("Déverrouiller Mémoire").setSubtitle("Accéder à ta mémoire personnelle").setNegativeButton("Code Android",getMainExecutor(),(dialog,w)->credentialUnlock()).build();prompt.authenticate(new CancellationSignal(),getMainExecutor(),new android.hardware.biometrics.BiometricPrompt.AuthenticationCallback(){public void onAuthenticationSucceeded(android.hardware.biometrics.BiometricPrompt.AuthenticationResult result){unlocked=true;page.setVisibility(View.VISIBLE);}public void onAuthenticationError(int code,CharSequence text){if(credentialPending)return;if(code==android.hardware.biometrics.BiometricPrompt.BIOMETRIC_ERROR_USER_CANCELED||code==android.hardware.biometrics.BiometricPrompt.BIOMETRIC_ERROR_CANCELED){finish();return;}credentialUnlock();}});}else credentialUnlock();
    }
    void credentialUnlock(){if(credentialPending)return;credentialPending=true;android.app.KeyguardManager manager=(android.app.KeyguardManager)getSystemService(KEYGUARD_SERVICE);Intent intent=manager.createConfirmDeviceCredentialIntent("Mémoire","Déverrouiller ta mémoire personnelle");if(intent!=null)startActivityForResult(intent,80);else finish();}
    void message(String s) { runOnUiThread(()->Toast.makeText(this,s,Toast.LENGTH_LONG).show()); }
    interface Task {void run()throws Exception;}
    void background(String text,Task task) {
        setRequestedOrientation(android.content.pm.ActivityInfo.SCREEN_ORIENTATION_LOCKED);
        ProgressDialog progress=new ProgressDialog(this);progress.setMessage(text);progress.setCancelable(false);progress.show();
        new Thread(()->{try{task.run();}catch(Exception e){message("Opération échouée : "+e.getMessage());runOnUiThread(()->home());}finally{runOnUiThread(()->{if(!isFinishing())progress.dismiss();setRequestedOrientation(android.content.pm.ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);});}},"memoire-files").start();
    }
    String screen="Accueil";
    int dp(float value){return Math.round(value*getResources().getDisplayMetrics().density);}
    boolean dark(){return (getResources().getConfiguration().uiMode&android.content.res.Configuration.UI_MODE_NIGHT_MASK)==android.content.res.Configuration.UI_MODE_NIGHT_YES;}
    int ink(){return android.graphics.Color.parseColor(dark()?"#EAF1EF":"#203731");}
    int muted(){return android.graphics.Color.parseColor(dark()?"#A4BAB2":"#6A7E76");}
    int surface(){return android.graphics.Color.parseColor(dark()?"#1B2D28":"#FFFFFF");}
    int accent(){return android.graphics.Color.parseColor(dark()?"#A4DCC7":"#286B54");}
    android.graphics.drawable.GradientDrawable shape(int color,int radius){android.graphics.drawable.GradientDrawable d=new android.graphics.drawable.GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    android.graphics.drawable.RippleDrawable touch(int color,int radius){return new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(android.graphics.Color.parseColor("#223A8C69")),shape(color,radius),shape(android.graphics.Color.WHITE,radius));}
    LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);return l;}
    LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(0);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    TextView text(String value,int size,int color){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);return t;}
    void section(LinearLayout parent,String value){TextView t=text(value,12,muted());t.setTypeface(null,1);t.setPadding(0,dp(20),0,dp(10));parent.addView(t);}
    void layout(String heading){
        page=column();page.setPadding(dp(20),dp(14),dp(20),dp(8));page.setBackgroundColor(android.graphics.Color.parseColor(dark()?"#11211D":"#F4F7F5"));
        getWindow().setStatusBarColor(android.graphics.Color.parseColor(dark()?"#11211D":"#F4F7F5"));getWindow().setNavigationBarColor(surface());
        getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
        TextView h=text(heading,30,ink());h.setTypeface(null,1);h.setPadding(0,dp(8),0,dp(6));page.addView(h);setContentView(page);if(db!=null&&db.optBoolean("appLock")&&!unlocked)page.setVisibility(View.INVISIBLE);
    }
    Button button(LinearLayout parent,String label,Runnable action){
        Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextSize(14);b.setTextColor(accent());b.setTypeface(null,1);b.setBackground(touch(surface(),14));b.setPadding(dp(10),dp(8),dp(10),dp(8));b.setMinHeight(dp(48));b.setMinimumWidth(0);b.setMinWidth(0);
        LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(parent.getOrientation()==0?0:-1,-2,parent.getOrientation()==0?1:0);lp.setMargins(dp(3),dp(4),dp(3),dp(4));parent.addView(b,lp);b.setOnClickListener(v->action.run());return b;
    }
    EditText input(LinearLayout parent,String hint,String value,boolean multi){
        EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setSingleLine(!multi);e.setGravity(Gravity.TOP);e.setTextSize(fontSize);e.setTextColor(ink());e.setHintTextColor(muted());e.setPadding(dp(14),dp(13),dp(14),dp(13));e.setBackground(shape(surface(),12));
        LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(4),0,dp(8));parent.addView(e,lp);return e;
    }
    void nav(){
        LinearLayout nav=row();nav.setPadding(0,dp(6),0,0);page.addView(nav);
        for(String name:new String[]{"Accueil","Fiches","Réglages"}){Button b=button(nav,name,()->{screen=name;trash=false;inbox=false;archive=false;home();});if(screen.equals(name)&&!trash){b.setBackground(touch(accent(),14));b.setTextColor(dark()?android.graphics.Color.parseColor("#11211D"):android.graphics.Color.WHITE);}}
    }
    void restorePrompt(){new AlertDialog.Builder(this).setTitle("Restaurer une sauvegarde").setItems(new String[]{"Fusionner toutes les fiches","Remplacer toutes mes données","Fusionner seulement l’espace actuel"},(d,w)->{mergeImport=w!=1;restoreScope=w==2?currentSpace:"";if(mergeImport)pick(IMPORT,"*/*");else new AlertDialog.Builder(this).setTitle("Remplacer toutes les données ?").setMessage("Exporte une sauvegarde avant de poursuivre.").setPositiveButton("Choisir",(dialog,k)->pick(IMPORT,"*/*")).setNegativeButton("Annuler",null).show();}).show();}
    void home(){
        saveEditor();editing=null;fields.clear();blockEditors.clear();list=null;if(db.optBoolean("appLock"))getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE,WindowManager.LayoutParams.FLAG_SECURE);else getWindow().clearFlags(WindowManager.LayoutParams.FLAG_SECURE);
        layout(trash?"Corbeille":inbox?"À classer":archive?"Archives":screen.equals("Accueil")?"Mémoire":screen);
        if(screen.equals("Réglages")&&!trash){
            ScrollView sc=new ScrollView(this);LinearLayout content=column();sc.addView(content);page.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
            section(content,"MES DONNÉES");button(content,"Exporter une sauvegarde complète",()->backupOptions());button(content,"Restaurer une sauvegarde",()->restorePrompt());button(content,"Ouvrir la corbeille",()->{trash=true;home();});
            button(content,"Bibliothèque de fichiers",()->fileLibrary());button(content,"Exporter en Markdown",()->exportMarkdown());
            section(content,"ORGANISATION");button(content,"Gérer les espaces",()->spaces());button(content,"Gérer les modèles",()->manageTemplates());button(content,"Recherches enregistrées",()->savedSearches());
            section(content,"CONFIDENTIALITÉ");button(content,db.optBoolean("appLock")?"Désactiver le verrouillage de Mémoire":"Verrouiller Mémoire à l’ouverture",()->{put(db,"appLock",!db.optBoolean("appLock"));persist();home();if(db.optBoolean("appLock"))unlock();});TextView info=text("Tes fiches restent sur ce téléphone. Aucun compte ni synchronisation. Conserve une sauvegarde sur un autre appareil.",15,muted());info.setLineSpacing(dp(5),1);content.addView(info);
            section(content,"SAUVEGARDE");content.addView(text(db.optLong("lastBackup")==0?"Aucune sauvegarde enregistrée":"Dernier export : "+new java.util.Date(db.optLong("lastBackup")),14,muted()));button(content,db.optBoolean("backupHint")?"Désactiver le rappel discret":"Afficher un rappel après 7 jours sans export",()->{put(db,"backupHint",!db.optBoolean("backupHint"));persist();home();});
            section(content,"APPARENCE");button(content,"Taille du texte : "+fontSize,()->new AlertDialog.Builder(this).setTitle("Taille du texte").setItems(new String[]{"Petite","Normale","Grande","Très grande"},(d,w)->{fontSize=new int[]{14,16,18,21}[w];put(db,"fontSize",fontSize);persist();home();}).show());content.addView(text("Le thème suit le mode clair ou sombre d’Android.",15,muted()));section(content,"MÉMOIRE 0.4.0");content.addView(text("Ta mémoire personnelle, toujours à portée de main.",15,muted()));nav();return;
        }
        page.addView(text(trash?"Retrouve tes fiches supprimées.":screen.equals("Accueil")?"Garde une trace. Retrouve tes idées.":"Toutes tes connaissances, au même endroit.",14,muted()));
        if(!trash){LinearLayout scope=row();page.addView(scope);button(scope,currentSpace+" ▾",()->spaces());button(scope,globalSearch?"Partout":"Cet espace",()->{globalSearch=!globalSearch;home();});}
        if(screen.equals("Accueil")&&!trash&&!inbox&&!archive){LinearLayout queues=row();page.addView(queues);button(queues,"À classer",()->{inbox=true;home();});button(queues,"Réviser",()->revision());button(queues,"Archives",()->{archive=true;home();});if(db.optBoolean("backupHint")&&System.currentTimeMillis()-db.optLong("lastBackup")>7L*86400000)page.addView(text("Pense à exporter une sauvegarde vers un autre appareil.",13,muted()));}
        EditText search=input(page,"Rechercher dans mes fiches…",query,false);search.setSingleLine(true);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){query=s.toString();render();}public void afterTextChanged(Editable e){}});
        if(screen.equals("Fiches")&&!trash){LinearLayout controls=row();page.addView(controls);button(controls,"Projets",()->projects());button(controls,"Modèles",()->templates());button(controls,filter.isEmpty()?"Filtrer":"Filtre actif",()->filters());}
        ScrollView sc=new ScrollView(this);list=column();sc.addView(list);page.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
        if(!trash){Button add=button(page,"＋  Nouvelle fiche",()->create());add.setBackground(touch(accent(),16));add.setTextColor(dark()?android.graphics.Color.parseColor("#11211D"):android.graphics.Color.WHITE);}else button(page,"← Retour aux réglages",()->{trash=false;screen="Réglages";home();});
        nav();render();
    }
    void card(JSONObject n){
        LinearLayout card=column();card.setPadding(dp(16),dp(15),dp(16),dp(15));card.setBackground(shape(surface(),16));card.setForeground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(android.graphics.Color.parseColor("#183A8C69")),null,shape(android.graphics.Color.WHITE,16)));card.setElevation(dp(1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(10));list.addView(card,lp);
        TextView title=text((n.optBoolean("favorite")?"★  ":"")+(n.optString("title").trim().isEmpty()?"Sans titre":n.optString("title")),17,ink());title.setTypeface(null,1);title.setMaxLines(2);title.setEllipsize(android.text.TextUtils.TruncateAt.END);card.addView(title);
        String excerpt=n.optString("body").replace('\n',' ').trim();if(!excerpt.isEmpty()){TextView body=text(excerpt,14,muted());body.setMaxLines(2);body.setEllipsize(android.text.TextUtils.TruncateAt.END);body.setPadding(0,dp(7),0,0);card.addView(body);}
        String meta=(globalSearch?n.optString("space")+" · ":"")+n.optString("project")+(n.optString("project").isEmpty()?"":" · ")+n.optString("tags");if(meta.isEmpty())meta=android.text.format.DateFormat.format("dd MMM · HH:mm",n.optLong("updated",System.currentTimeMillis())).toString();TextView subtitle=text(meta,12,accent());subtitle.setPadding(0,dp(10),0,0);card.addView(subtitle);card.setOnClickListener(v->edit(n));card.setContentDescription("Ouvrir la fiche "+title.getText());
    }
    void render(){
        if(list==null)return;list.removeAllViews();List<JSONObject> sorted=new ArrayList<>();
        for(int i=0;i<notes.length();i++){JSONObject n=notes.optJSONObject(i);if(n!=null&&n.optBoolean("deleted")==trash&&(globalSearch||n.optString("space","Études").equals(currentSpace))&&(!inbox||n.optBoolean("inbox"))&&(trash||n.optBoolean("archived")==archive)&&SearchEngine.match(LocalStore.searchable(n),query)&&(!screen.equals("Fiches")||filter.isEmpty()||LocalStore.normalized(n.optString("tags")).contains(LocalStore.normalized(filter)))&&(projectFilter.isEmpty()||n.optString("project").equals(projectFilter))&&(statusFilter.isEmpty()||n.optString("status").equals(statusFilter))&&(!onlyFavorites||n.optBoolean("favorite"))&&n.optLong("updated")>=afterDate)sorted.add(n);}

        boolean overview=screen.equals("Accueil")&&!trash&&!inbox&&!archive&&query.isEmpty();
        if(overview){sorted.sort((a,b)->Long.compare(b.optLong("updated"),a.optLong("updated")));List<JSONObject> favorites=new ArrayList<>();for(JSONObject n:sorted)if(n.optBoolean("favorite"))favorites.add(n);if(!favorites.isEmpty()){section(list,"FAVORIS");for(int i=0;i<Math.min(3,favorites.size());i++)card(favorites.get(i));}section(list,"RÉCEMMENT MODIFIÉES");for(int i=0;i<Math.min(8,sorted.size());i++)card(sorted.get(i));}
        else{sorted.sort((a,b)->Long.compare(b.optLong("updated"),a.optLong("updated")));section(list,sorted.size()+" FICHE"+(sorted.size()>1?"S":""));for(JSONObject n:sorted)card(n);}
        if(sorted.isEmpty()){TextView empty=text(query.isEmpty()?trash?"La corbeille est vide.":"Une solution, un cours, une idée…\nCrée ta première fiche pour la retrouver plus tard.":"Aucune fiche ne correspond à ta recherche.",16,muted());empty.setPadding(dp(12),dp(32),dp(12),dp(32));empty.setGravity(Gravity.CENTER);list.addView(empty);}
    }
    void create() {
        saveEditor();
        JSONObject n=new JSONObject(); put(n,"id",UUID.randomUUID().toString()); put(n,"updated",System.currentTimeMillis()); put(n,"title",""); put(n,"body",""); put(n,"tags",""); put(n,"space",currentSpace);put(n,"inbox",true);put(n,"status","À classer");put(n,"blocks",new JSONArray());put(n,"fields",new JSONArray()); put(n,"files",new JSONArray()); put(n,"versions",new JSONArray()); notes.put(n); persist(); edit(n);
    }
    void edit(JSONObject n) {
        saveEditor(); editing=null; fields.clear();blockEditors.clear();
        layout("Ma fiche");
        LinearLayout header=row();page.addView(header);button(header,"← Retour",()->home());button(header,"Aperçu",()->preview());button(header,"•••",()->noteMenu(n));
        ScrollView s=new ScrollView(this); LinearLayout content=column(); s.addView(content); page.addView(s,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout classification=row();content.addView(classification);button(classification,n.optString("space","Études"),()->classify(n));button(classification,n.optString("status","À classer"),()->setStatus(n));
        if(!n.optString("project").isEmpty())content.addView(text("Projet / matière : "+n.optString("project"),14,accent()));
        section(content,"L’ESSENTIEL");
        title=input(content,"Titre de la fiche",n.optString("title"),false);title.setTextSize(23);title.setTypeface(null,1);
        tags=input(content,"Étiquettes séparées par des virgules",n.optString("tags"),false);
        section(content,"NOTES");
        body=input(content,"Notes, solution, étapes, code…",n.optString("body"),true); body.setMinLines(7);
        JSONArray fs=n.optJSONArray("fields");
        if(fs.length()>0)section(content,"CHAMPS PERSONNALISÉS");
        for(int i=0;i<fs.length();i++) {
            JSONObject f=fs.optJSONObject(i); String id=f.optString("id");
            LinearLayout fieldHeader=row();content.addView(fieldHeader);TextView label=text(f.optString("name")+(f.optBoolean("required")?" *":""),14,muted());label.setTypeface(null,1);fieldHeader.addView(label,new LinearLayout.LayoutParams(0,-2,3));Button fieldOptions=button(fieldHeader,"•••",()->fieldMenu(n,f));fieldOptions.setLayoutParams(new LinearLayout.LayoutParams(dp(48),dp(48)));fieldOptions.setContentDescription("Options du champ "+f.optString("name"));
            EditText e=input(content,f.optString("name"),f.optString("value"),true); fields.put(id,e);
            String type=f.optString("type");
            if(type.equals("Nombre"))e.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL|android.text.InputType.TYPE_NUMBER_FLAG_SIGNED);
            if(type.equals("Code")) e.setTypeface(android.graphics.Typeface.MONOSPACE);
            if(type.equals("Lien web")) e.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_URI);
            if(type.equals("Case à cocher")) {e.setVisibility(View.GONE);CheckBox box=new CheckBox(this);box.setText(f.optString("name"));box.setChecked("true".equals(f.optString("value")));content.addView(box);box.setOnCheckedChangeListener((v,checked)->e.setText(Boolean.toString(checked)));}
            if(type.equals("Date")) {e.setFocusable(false);e.setOnClickListener(v->{Calendar c=Calendar.getInstance();new DatePickerDialog(this,(picker,y,m,d)->e.setText(String.format(Locale.ROOT,"%04d-%02d-%02d",y,m+1,d)),c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show();});}
            if(type.equals("Choix")||type.equals("Choix multiples")) {e.setFocusable(false);e.setOnClickListener(v->{String[] choices=f.optString("options").split("\\n");if(type.equals("Choix"))new AlertDialog.Builder(this).setTitle(f.optString("name")).setItems(choices,(dialog,index)->e.setText(choices[index])).show();else{Set<String> chosen=new LinkedHashSet<>(Arrays.asList(e.getText().toString().split("\\n")));boolean[] selected=new boolean[choices.length];for(int j=0;j<choices.length;j++)selected[j]=chosen.contains(choices[j]);new AlertDialog.Builder(this).setTitle(f.optString("name")).setMultiChoiceItems(choices,selected,(dialog,index,checked)->{if(checked)chosen.add(choices[index]);else chosen.remove(choices[index]);}).setPositiveButton("Valider",(dialog,w)->{chosen.remove("");e.setText(String.join("\n",chosen));}).show();}});}
            if(type.startsWith("Relation")) {e.setVisibility(View.GONE);button(content,"Choisir une fiche liée",()->chooseRelation(e,n));button(content,"Ouvrir la fiche liée",()->{String target=e.getText().toString();for(int j=0;j<notes.length();j++){JSONObject linked=notes.optJSONObject(j);if(linked.optString("id").equals(target)){edit(linked);return;}}message("Choisis une fiche liée.");});}
        }
        renderBlocks(content,n);
        JSONArray files=n.optJSONArray("files");if(files.length()>0)section(content,"PIÈCES JOINTES");
        for(int i=0;i<files.length();i++){JSONObject f=files.optJSONObject(i);button(content,"↗  "+f.optString("name"),()->attachmentMenu(n,f));}
        TextView status=text("Enregistrement automatique sur ce téléphone",12,muted());status.setPadding(0,dp(20),0,dp(16));content.addView(status);
        LinearLayout tools=row();page.addView(tools);button(tools,"＋ Champ",()->addField());button(tools,"Fichier",()->pick(ATTACH,"*/*"));button(tools,"Bloc",()->addBlock());
        editing=n;
        TextWatcher watcher=new TextWatcher(){ public void beforeTextChanged(CharSequence s,int a,int c,int d){} public void onTextChanged(CharSequence s,int a,int b,int c){handler.removeCallbacks(autosave);handler.postDelayed(autosave,600);}public void afterTextChanged(Editable e){} };
        title.addTextChangedListener(watcher); tags.addTextChangedListener(watcher); body.addTextChangedListener(watcher); for(EditText e:fields.values()) e.addTextChangedListener(watcher);for(EditText e:blockEditors.values())e.addTextChangedListener(watcher);
    }
    void noteMenu(JSONObject n){
        String[] choices={n.optBoolean("favorite")?"Retirer des favoris":"Ajouter aux favoris","Programmer un rappel","Créer un modèle depuis cette fiche","Historique des versions",n.optBoolean("deleted")?"Restaurer la fiche":"Mettre à la corbeille","Classer ou déplacer","Archiver / désarchiver","Exporter cette fiche en PDF","Supprimer définitivement"};
        new AlertDialog.Builder(this).setTitle("Options de la fiche").setItems(choices,(dialog,index)->{saveEditor();if(index==0){put(n,"favorite",!n.optBoolean("favorite"));persist();edit(n);}else if(index==1)reminder(n);else if(index==2)saveTemplate(n);else if(index==3)history(n);else if(index==5)classify(n);else if(index==6){put(n,"archived",!n.optBoolean("archived"));persist();home();}else if(index==7)exportPdf(n);else if(index==8)purge(n);else new AlertDialog.Builder(this).setTitle(choices[index]+" ?").setPositiveButton("Confirmer",(d,w)->{put(n,"deleted",!n.optBoolean("deleted"));persist();home();}).setNegativeButton("Annuler",null).show();}).show();
    }
    void fieldMenu(JSONObject n,JSONObject f){
        new AlertDialog.Builder(this).setTitle(f.optString("name")).setItems(new String[]{"Monter ce champ","Supprimer ce champ","Renommer","Obligatoire / facultatif"},(dialog,index)->{if(index==0)moveField(n,f.optString("id"));else if(index==2){EditText label=new EditText(this);label.setText(f.optString("name"));new AlertDialog.Builder(this).setTitle("Nom du champ").setView(label).setPositiveButton("Enregistrer",(x,y)->{saveEditor();String value=label.getText().toString().trim();if(!value.isEmpty()){put(f,"name",value);persist();edit(n);}}).show();}else if(index==3){saveEditor();put(f,"required",!f.optBoolean("required"));persist();edit(n);}else new AlertDialog.Builder(this).setTitle("Supprimer ce champ ?").setMessage("Sa valeur actuelle sera supprimée. Une ancienne version peut rester dans l’historique.").setPositiveButton("Supprimer",(d,w)->{saveEditor();JSONArray fs=n.optJSONArray("fields");for(int j=0;j<fs.length();j++)if(fs.optJSONObject(j).optString("id").equals(f.optString("id"))){fs.remove(j);break;}persist();editing=null;edit(n);}).setNegativeButton("Annuler",null).show();}).show();
    }
    JSONObject snapshot(JSONObject n)throws Exception{JSONObject base=new JSONObject();Iterator<String> keys=n.keys();while(keys.hasNext()){String key=keys.next();if(!key.equals("versions"))base.put(key,n.opt(key));}return new JSONObject(base.toString());}
    String snapshotText(JSONObject n){try{return snapshot(n).toString();}catch(Exception e){return "";}}
    void saveEditor() {
        handler.removeCallbacks(autosave);
        if(editing==null||title==null)return;
        JSONObject previous;String before;
        try{previous=snapshot(editing);before=previous.toString();}catch(Exception e){message("Impossible de créer la version précédente");return;}
        put(editing,"title",title.getText().toString()); put(editing,"body",body.getText().toString());put(editing,"tags",tags.getText().toString());
        JSONArray fs=editing.optJSONArray("fields");
        for(int i=0;i<fs.length();i++) { JSONObject f=fs.optJSONObject(i);EditText e=fields.get(f.optString("id"));if(e!=null){put(f,"value",e.getText().toString());if(f.optBoolean("required")&&e.getText().toString().trim().isEmpty())e.setError("À compléter");} }
        JSONArray blocks=editing.optJSONArray("blocks");if(blocks!=null)for(int i=0;i<blocks.length();i++){JSONObject block=blocks.optJSONObject(i);EditText e=blockEditors.get(block.optString("id"));if(e!=null)put(block,"text",e.getText().toString());else if(block.optString("type").equals("Question / réponse")){EditText q=blockEditors.get(block.optString("id")+".question"),a=blockEditors.get(block.optString("id")+".answer");if(q!=null&&a!=null)put(block,"text",q.getText().toString()+"\n---\n"+a.getText().toString());}}
        if(!before.equals(snapshotText(editing))) {
            JSONArray versions=editing.optJSONArray("versions");
            // Coalesce changes in one editing session minute to avoid a version per keystroke.
            if(versions.length()==0||System.currentTimeMillis()-versions.optJSONObject(versions.length()-1).optLong("snapshotAt")>60000) {put(previous,"snapshotAt",System.currentTimeMillis());versions.put(previous);}
            while(versions.length()>20)versions.remove(0);
            put(editing,"updated",System.currentTimeMillis());persist();
        }
    }
    void addField() {
        saveEditor(); LinearLayout l=column();EditText name=input(l,"Nom du champ","",false);
        Spinner type=new Spinner(this);String[] types={"Texte","Texte long","Code","Nombre","Date","Lien web","Liste","Choix","Choix multiples","Case à cocher","Relation"};type.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,types));l.addView(type);EditText options=input(l,"Options de choix : une par ligne","",true);
        new AlertDialog.Builder(this).setTitle("Nouveau champ").setView(l).setPositiveButton("Ajouter",(d,w)->{if(name.getText().toString().trim().isEmpty()){message("Un nom est nécessaire.");return;}JSONObject f=new JSONObject();put(f,"id",UUID.randomUUID().toString());put(f,"name",name.getText().toString());put(f,"type",type.getSelectedItem().toString());put(f,"value","");put(f,"options",options.getText().toString());editing.optJSONArray("fields").put(f);persist();edit(editing);}).setNegativeButton("Annuler",null).show();
    }
    void reminder(JSONObject n) {
        saveEditor();
        if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS)!=android.content.pm.PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},40);message("Autorise les notifications puis choisis à nouveau le rappel.");return;}
        Calendar c=Calendar.getInstance();new AlertDialog.Builder(this).setTitle("Rappel facultatif").setMessage("Android peut retarder la notification pour économiser la batterie.").setPositiveButton("Choisir date et heure",(dialog,w)->new DatePickerDialog(this,(picker,y,m,d)->{c.set(y,m,d);new TimePickerDialog(this,(time,h,min)->{c.set(Calendar.HOUR_OF_DAY,h);c.set(Calendar.MINUTE,min);c.set(Calendar.SECOND,0);if(c.getTimeInMillis()<=System.currentTimeMillis()){message("Choisis une date future.");return;}put(n,"reminder",c.getTimeInMillis());persist();ReminderReceiver.schedule(this,n.optString("id"),n.optString("title"),n.optLong("reminder"));edit(n);},c.get(Calendar.HOUR_OF_DAY),c.get(Calendar.MINUTE),true).show();},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show()).setNeutralButton("Supprimer le rappel",(dialog,w)->{put(n,"reminder",0);ReminderReceiver.schedule(this,n.optString("id"),n.optString("title"),0);persist();edit(n);}).setNegativeButton("Annuler",null).show();
    }
    String searchable(JSONObject n) {
        StringBuilder text=new StringBuilder(n.optString("title")).append(' ').append(n.optString("body")).append(' ').append(n.optString("tags"));
        JSONArray fs=n.optJSONArray("fields");if(fs!=null)for(int i=0;i<fs.length();i++){JSONObject f=fs.optJSONObject(i);text.append(' ').append(f.optString("name")).append(' ').append(f.optString("value"));}
        JSONArray files=n.optJSONArray("files");if(files!=null)for(int i=0;i<files.length();i++)text.append(' ').append(files.optJSONObject(i).optString("name"));
        return text.toString().toLowerCase(Locale.ROOT);
    }
    void filters(){LinearLayout l=column();EditText tag=input(l,"Étiquette",filter,false);EditText project=input(l,"Projet ou matière",projectFilter,false);Spinner status=new Spinner(this);String[] choices={"Tous les états","À classer","En cours","Résolu","À revoir","Terminé"};status.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,choices));int selected=Arrays.asList(choices).indexOf(statusFilter);status.setSelection(Math.max(0,selected));l.addView(status);CheckBox favorite=new CheckBox(this);favorite.setText("Favoris uniquement");favorite.setChecked(onlyFavorites);l.addView(favorite);final long[] date={afterDate};button(l,afterDate==0?"Modifiées depuis une date…":new java.util.Date(afterDate).toString(),()->{Calendar c=Calendar.getInstance();new DatePickerDialog(this,(v,y,m,d)->{c.set(y,m,d,0,0,0);c.set(Calendar.MILLISECOND,0);date[0]=c.getTimeInMillis();},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show();});new AlertDialog.Builder(this).setTitle("Filtres").setView(l).setPositiveButton("Appliquer",(d,w)->{filter=tag.getText().toString().trim();projectFilter=project.getText().toString().trim();statusFilter=status.getSelectedItemPosition()==0?"":status.getSelectedItem().toString();onlyFavorites=favorite.isChecked();afterDate=date[0];home();}).setNeutralButton("Tout effacer",(d,w)->{filter="";projectFilter="";statusFilter="";onlyFavorites=false;afterDate=0;home();}).setNegativeButton("Annuler",null).show();}
    void chooseRelation(EditText field,JSONObject current) {
        List<JSONObject> choices=new ArrayList<>();for(int i=0;i<notes.length();i++){JSONObject n=notes.optJSONObject(i);if(n!=current&&!n.optBoolean("deleted"))choices.add(n);}
        String[] names=new String[choices.size()];for(int i=0;i<names.length;i++)names[i]=choices.get(i).optString("title");new AlertDialog.Builder(this).setTitle("Lier à une fiche").setItems(names,(d,w)->field.setText(choices.get(w).optString("id"))).setNeutralButton("Retirer le lien",(d,w)->field.setText("")).show();
    }
    void saveTemplate(JSONObject n) {
        saveEditor();EditText name=new EditText(this);name.setHint("Nom du modèle");new AlertDialog.Builder(this).setTitle("Créer un modèle").setView(name).setPositiveButton("Enregistrer",(d,w)->{if(name.getText().toString().trim().isEmpty())return;try{JSONObject t=new JSONObject();put(t,"name",name.getText().toString().trim());JSONArray fs=new JSONArray(n.getJSONArray("fields").toString());for(int i=0;i<fs.length();i++)put(fs.getJSONObject(i),"value","");put(t,"fields",fs);db.getJSONArray("templates").put(t);persist();message("Modèle enregistré.");}catch(Exception e){message(e.getMessage());}}).setNegativeButton("Annuler",null).show();
    }
    void templates() {
        JSONArray ts=db.optJSONArray("templates");if(ts==null||ts.length()==0){message("Crée une fiche avec des champs puis enregistre sa structure comme modèle.");return;}
        String[] names=new String[ts.length()];for(int i=0;i<names.length;i++)names[i]=ts.optJSONObject(i).optString("name");new AlertDialog.Builder(this).setTitle("Créer depuis un modèle").setItems(names,(d,w)->{create();try{JSONArray fs=new JSONArray(ts.getJSONObject(w).getJSONArray("fields").toString());for(int i=0;i<fs.length();i++)put(fs.getJSONObject(i),"id",UUID.randomUUID().toString());put(editing,"fields",fs);put(editing,"template",names[w]);persist();edit(editing);}catch(Exception e){message(e.getMessage());}}).show();
    }
    void moveField(JSONObject n,String id) {
        saveEditor();JSONArray old=n.optJSONArray("fields");List<JSONObject> ordered=new ArrayList<>();int index=-1;for(int j=0;j<old.length();j++){JSONObject f=old.optJSONObject(j);ordered.add(f);if(f.optString("id").equals(id))index=j;}if(index<=0)return;Collections.swap(ordered,index,index-1);JSONArray next=new JSONArray();for(JSONObject f:ordered)next.put(f);put(n,"fields",next);persist();editing=null;edit(n);
    }
    void preview() {
        saveEditor();android.text.SpannableStringBuilder rich=new android.text.SpannableStringBuilder();boolean code=false;
        for(String line:(editing==null?body.getText().toString():markdown(editing)).split("\\n",-1)) {
            if(line.startsWith("```")){code=!code;continue;}
            boolean heading=!code&&line.startsWith("#");boolean quote=!code&&line.startsWith(">");String text=line;
            if(heading)text=line.replaceFirst("^#+\\s*","");else if(quote)text=line.replaceFirst("^>\\s*","");else if(!code&&line.startsWith("- "))text="• "+line.substring(2);
            int start=rich.length();rich.append(text).append('\n');int end=rich.length();
            if(heading){rich.setSpan(new android.text.style.StyleSpan(android.graphics.Typeface.BOLD),start,end,33);rich.setSpan(new android.text.style.RelativeSizeSpan(1.3f),start,end,33);}
            if(quote)rich.setSpan(new android.text.style.StyleSpan(android.graphics.Typeface.ITALIC),start,end,33);
            if(code)rich.setSpan(new android.text.style.TypefaceSpan("monospace"),start,end,33);
        }
        TextView view=new TextView(this);view.setText(rich);view.setTextSize(17);view.setTextIsSelectable(true);view.setPadding(24,24,24,24);ScrollView scroll=new ScrollView(this);scroll.addView(view);new AlertDialog.Builder(this).setTitle(title.getText().toString()).setView(scroll).setPositiveButton("Fermer",null).show();
    }
    void addMarkdownSnippet() {
        String[] kinds={"Titre","Liste","Code","Citation"};new AlertDialog.Builder(this).setTitle("Insérer dans la note (Markdown)").setItems(kinds,(d,w)->{String[] snippets={"\n## Titre\n","\n- Élément\n- Élément\n","\n```\ncode\n```\n","\n> Citation\n"};int position=Math.max(0,body.getSelectionStart());body.getText().insert(position,snippets[w]);}).show();
    }
    void openAttachment(JSONObject f) {
        try {Uri uri=new Uri.Builder().scheme("content").authority("bf.memoire.files").appendPath(f.optString("id")).appendPath(f.optString("name")).build();String type=getContentResolver().getType(uri);Intent intent=new Intent(Intent.ACTION_VIEW).setDataAndType(uri,type).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(intent,"Ouvrir le fichier"));}catch(Exception e){message("Aucune application compatible pour ouvrir ce fichier.");}
    }
    void history(JSONObject n) {
        saveEditor();JSONArray vs=n.optJSONArray("versions");String[] labels=new String[vs.length()];for(int i=0;i<vs.length();i++)labels[i]=new java.util.Date(vs.optJSONObject(i).optLong("snapshotAt")).toString();
        new AlertDialog.Builder(this).setTitle("Restaurer une version").setItems(labels,(d,w)->{JSONObject v=vs.optJSONObject(w);put(n,"title",v.optString("title"));put(n,"body",v.optString("body"));put(n,"tags",v.optString("tags"));for(String key:new String[]{"space","project","status","inbox","archived"})if(v.has(key))put(n,key,v.opt(key));try{put(n,"fields",new JSONArray(v.optJSONArray("fields").toString()));if(v.optJSONArray("blocks")!=null)put(n,"blocks",new JSONArray(v.optJSONArray("blocks").toString()));if(v.optJSONArray("files")!=null)put(n,"files",new JSONArray(v.optJSONArray("files").toString()));}catch(Exception e){message("Version invalide");return;}editing=null;persist();edit(n);}).setNegativeButton("Fermer",null).show();
    }
    void pick(int code,String mime) {saveEditor();Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(mime);startActivityForResult(i,code);}
    void attach(Uri uri) {
        if(editing==null)return;saveEditor();JSONObject owner=editing;String replace=replacingFile;replacingFile="";String blockType=pendingBlockType;pendingBlockType="";editing=null;
        background("Copie du fichier…",()->{
            String name="Fichier";try(Cursor c=getContentResolver().query(uri,null,null,null,null)){if(c!=null&&c.moveToFirst()){int idx=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(idx>=0)name=c.getString(idx);}}
            String id=UUID.randomUUID().toString();File dir=new File(getFilesDir(),"attachments");dir.mkdirs();File dest=new File(dir,id);
            try(InputStream in=getContentResolver().openInputStream(uri);FileOutputStream out=new FileOutputStream(dest)){if(in==null)throw new IOException("Fichier inaccessible");copy(in,out);}catch(Exception e){dest.delete();runOnUiThread(()->edit(owner));throw e;}
            String finalId=id;String fingerprint=hash(dest);File[] existing=new File(getFilesDir(),"attachments").listFiles();if(existing!=null)for(File candidate:existing){if(candidate.equals(dest)||candidate.length()!=dest.length())continue;if(hash(candidate).equals(fingerprint)){finalId=candidate.getName();dest.delete();break;}}
            JSONObject f=new JSONObject();put(f,"id",finalId);put(f,"name",name);put(f,"sha256",fingerprint);runOnUiThread(()->{if(!replace.isEmpty()){JSONArray files=owner.optJSONArray("files");for(int i=0;i<files.length();i++)if(files.optJSONObject(i).optString("id").equals(replace)){files.remove(i);break;}JSONArray blocks=owner.optJSONArray("blocks");if(blocks!=null)for(int i=0;i<blocks.length();i++)if(blocks.optJSONObject(i).optString("fileId").equals(replace))put(blocks.optJSONObject(i),"fileId",f.optString("id"));}addAttachmentRecord(owner,f,blockType);persist();edit(owner);});
        });
    }
    void exportData(){saveEditor();Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType(archivePassword==null?"application/zip":"application/octet-stream").putExtra(Intent.EXTRA_TITLE,"Memoire-"+System.currentTimeMillis()+(archivePassword==null?".zip":".memoire"));startActivityForResult(i,EXPORT);}
    void writeBackup(OutputStream destination)throws Exception{try(ZipOutputStream z=new ZipOutputStream(destination)){z.putNextEntry(new ZipEntry("memory.json"));z.write(db.toString().getBytes("UTF-8"));z.closeEntry();File[] files=new File(getFilesDir(),"attachments").listFiles();if(files!=null)for(File f:files){if(!f.isFile())continue;z.putNextEntry(new ZipEntry("attachments/"+f.getName()));try(InputStream in=new FileInputStream(f)){copy(in,z);}z.closeEntry();}}}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);
        if(request==80){credentialPending=false;if(result==RESULT_OK){unlocked=true;page.setVisibility(View.VISIBLE);}else finish();return;}
        if(request==60){finishCamera(result);return;}
        if(result!=RESULT_OK||data==null||data.getData()==null){pendingBlockType="";if(archivePassword!=null)Arrays.fill(archivePassword,'\0');archivePassword=null;return;}
        if(request==EXPORT&&pendingExportEncrypted&&archivePassword==null){message("Le mot de passe a été effacé lors du changement d’écran. Recommence l’export chiffré.");pendingExportEncrypted=false;return;}
        Uri uri=data.getData();if(request==ATTACH||request==61){if(request==61)pendingBlockType="Image";attach(uri);return;}
        if(request==IMPORT){try(InputStream in=getContentResolver().openInputStream(uri)){if(SecureArchive.encrypted(in)){password("Ouvrir la sauvegarde chiffrée",false,value->{archivePassword=value;importArchive(uri);});return;}}catch(Exception e){message("Sauvegarde inaccessible");return;}archivePassword=null;importArchive(uri);return;}
        saveEditor();editing=null;
        background("Création de l’export…",()->{
            if(request==EXPORT){try{if(archivePassword==null)writeBackup(getContentResolver().openOutputStream(uri));else{File zip=new File(getCacheDir(),"backup-"+UUID.randomUUID()+".zip");try{writeBackup(new FileOutputStream(zip));SecureArchive.encrypt(zip,getContentResolver().openOutputStream(uri),archivePassword);}finally{zip.delete();}}put(db,"lastBackup",System.currentTimeMillis());store.save(db);message("Sauvegarde exportée et terminée.");}finally{if(archivePassword!=null)Arrays.fill(archivePassword,'\0');archivePassword=null;pendingExportEncrypted=false;}}
            else if(request==50){try(ZipOutputStream z=new ZipOutputStream(getContentResolver().openOutputStream(uri))){for(int i=0;i<notes.length();i++){JSONObject n=notes.optJSONObject(i);if(n.optBoolean("deleted"))continue;String space=n.optString("space","Études").replaceAll("[^\\p{L}\\p{N}_-]","_");z.putNextEntry(new ZipEntry(space+"/"+n.optString("id")+"/fiche.md"));z.write(markdown(n).getBytes("UTF-8"));z.closeEntry();}File[] files=new File(getFilesDir(),"attachments").listFiles();if(files!=null)for(File f:files){z.putNextEntry(new ZipEntry("attachments/"+f.getName()));try(InputStream in=new FileInputStream(f)){copy(in,z);}z.closeEntry();}}message("Documents Markdown et fichiers exportés.");}
            runOnUiThread(()->home());
        });
    }
    void importArchive(Uri uri){saveEditor();editing=null;background("Vérification et restauration…",()->{try{restore(uri);}finally{if(archivePassword!=null)Arrays.fill(archivePassword,'\0');archivePassword=null;}});}
    void restore(Uri uri)throws Exception {
        File staging=new File(getCacheDir(),"restore-"+UUID.randomUUID());staging.mkdirs();
        try {
            InputStream source;if(archivePassword!=null){File decrypted=new File(staging,"decrypted.zip");SecureArchive.decrypt(getContentResolver().openInputStream(uri),decrypted,archivePassword);source=new FileInputStream(decrypted);}else source=getContentResolver().openInputStream(uri);
            JSONObject imported=BackupArchive.unpack(source,staging);
            JSONArray ns=imported.getJSONArray("notes");for(int i=0;i<ns.length();i++){JSONObject n=ns.getJSONObject(i);if(!n.has("space"))put(n,"space","Études");if(!n.has("blocks"))put(n,"blocks",new JSONArray());}
            JSONObject replacement=imported;
            File live=new File(getFilesDir(),"attachments");File incoming=new File(staging,"attachments");if(!incoming.exists())incoming.mkdirs();
            if(mergeImport){
                replacement=new JSONObject(db.toString());JSONArray merged=replacement.getJSONArray("notes");Map<String,JSONObject> existing=new HashMap<>();for(int i=0;i<merged.length();i++)existing.put(merged.getJSONObject(i).getString("id"),merged.getJSONObject(i));
                // Keep existing fiches on ID conflicts; never silently overwrite local work.
                for(int i=0;i<ns.length();i++){JSONObject n=ns.getJSONObject(i);if((restoreScope.isEmpty()||n.optString("space").equals(restoreScope))&&!existing.containsKey(n.getString("id")))merged.put(n);}
                File mergedFiles=new File(staging,"merged-files");mergedFiles.mkdirs();File[] local=live.listFiles();if(local!=null)for(File f:local)try(InputStream in=new FileInputStream(f);OutputStream out=new FileOutputStream(new File(mergedFiles,f.getName()))){copy(in,out);}
                File[] restored=incoming.listFiles();if(restored!=null)for(File f:restored){File target=new File(mergedFiles,f.getName());if(target.exists()&&!hash(target).equals(hash(f)))throw new IOException("Conflit de fichier : fusion annulée sans modifier les données");if(!target.exists())try(InputStream in=new FileInputStream(f);OutputStream out=new FileOutputStream(target)){copy(in,out);}}
                incoming=mergedFiles;
                JSONArray spaces=replacement.optJSONArray("spaces");if(spaces==null){spaces=new JSONArray();put(replacement,"spaces",spaces);}Set<String> names=new HashSet<>();for(int i=0;i<spaces.length();i++)names.add(spaces.optString(i));JSONArray restoredSpaces=imported.optJSONArray("spaces");if(restoredSpaces!=null)for(int i=0;i<restoredSpaces.length();i++)if(names.add(restoredSpaces.optString(i)))spaces.put(restoredSpaces.optString(i));
                JSONArray templates=replacement.optJSONArray("templates");JSONArray importedTemplates=imported.optJSONArray("templates");if(templates!=null&&importedTemplates!=null){Set<String> templateNames=new HashSet<>();for(int i=0;i<templates.length();i++)templateNames.add(templates.optJSONObject(i).optString("name"));for(int i=0;i<importedTemplates.length();i++)if(templateNames.add(importedTemplates.optJSONObject(i).optString("name")))templates.put(importedTemplates.optJSONObject(i));}
            }
            if(replacement.optJSONArray("spaces")==null)put(replacement,"spaces",new JSONArray(Arrays.asList("Études","Travail","Personnel","Projets")));if(replacement.optJSONArray("templates")==null)put(replacement,"templates",new JSONArray());
            ArchiveValidation.validateWithFiles(replacement,incoming);
            File old=new File(getFilesDir(),"attachments-old-"+UUID.randomUUID());boolean had=live.exists();if(had&&!live.renameTo(old))throw new IOException("Impossible de déplacer les fichiers");if(!incoming.renameTo(live)){if(had)old.renameTo(live);throw new IOException("Impossible de restaurer les fichiers");}
            try{store.save(replacement);}catch(Exception e){deleteTree(live);if(had)old.renameTo(live);throw e;}
            db=replacement;notes=db.getJSONArray("notes");currentSpace=db.optString("lastSpace",db.optJSONArray("spaces").optString(0,"Études"));fontSize=db.optInt("fontSize",16);query="";filter="";projectFilter="";statusFilter="";afterDate=0;onlyFavorites=false;deleteTree(old);for(int i=0;i<notes.length();i++){JSONObject n=notes.optJSONObject(i);if(!n.optBoolean("deleted"))ReminderReceiver.schedule(this,n.optString("id"),n.optString("title"),n.optLong("reminder"));}editing=null;runOnUiThread(()->{home();message(mergeImport?"Fusion terminée. Les fiches déjà présentes ont été conservées.":"Sauvegarde restaurée.");});
        }finally{deleteTree(staging);}
    }
    String hash(File file)throws Exception {java.security.MessageDigest md=java.security.MessageDigest.getInstance("SHA-256");try(InputStream in=new FileInputStream(file)){byte[] buffer=new byte[8192];int count;while((count=in.read(buffer))!=-1)md.update(buffer,0,count);}StringBuilder result=new StringBuilder();for(byte b:md.digest())result.append(String.format(Locale.ROOT,"%02x",b));return result.toString();}
    void spaces(){
        JSONArray spaces=db.optJSONArray("spaces");String[] names=new String[spaces.length()];for(int i=0;i<names.length;i++)names[i]=spaces.optString(i);
        new AlertDialog.Builder(this).setTitle("Mes espaces").setItems(names,(d,w)->{currentSpace=names[w];projectFilter="";statusFilter="";filter="";put(db,"lastSpace",currentSpace);persist();home();}).setNeutralButton("Créer",(d,w)->{EditText name=new EditText(this);name.setHint("Nom de l’espace");new AlertDialog.Builder(this).setTitle("Nouvel espace").setView(name).setPositiveButton("Créer",(dialog,k)->{String value=name.getText().toString().trim();if(value.isEmpty()||Arrays.asList(names).contains(value))return;spaces.put(value);currentSpace=value;put(db,"lastSpace",value);persist();home();}).show();}).setPositiveButton("Renommer l’espace actuel",(d,w)->{EditText name=new EditText(this);name.setText(currentSpace);new AlertDialog.Builder(this).setTitle("Renommer").setView(name).setPositiveButton("Enregistrer",(dialog,k)->{String value=name.getText().toString().trim();if(value.isEmpty()||Arrays.asList(names).contains(value))return;String previous=currentSpace;for(int i=0;i<spaces.length();i++)if(spaces.optString(i).equals(previous))try{spaces.put(i,value);}catch(Exception ignored){}for(int i=0;i<notes.length();i++){JSONObject n=notes.optJSONObject(i);if(n.optString("space").equals(previous))put(n,"space",value);}currentSpace=value;put(db,"lastSpace",value);persist();home();}).show();}).show();
    }
    void classify(JSONObject n){
        saveEditor();LinearLayout l=column();Spinner space=new Spinner(this);List<String> names=new ArrayList<>();JSONArray spaces=db.optJSONArray("spaces");for(int i=0;i<spaces.length();i++)names.add(spaces.optString(i));space.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names));space.setSelection(Math.max(0,names.indexOf(n.optString("space",currentSpace))));l.addView(space);
        AutoCompleteTextView project=new AutoCompleteTextView(this);project.setHint("Projet ou matière (facultatif)");project.setText(n.optString("project"));Set<String> projects=new TreeSet<>();for(int i=0;i<notes.length();i++){String value=notes.optJSONObject(i).optString("project");if(!value.isEmpty())projects.add(value);}project.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_dropdown_item_1line,new ArrayList<>(projects)));l.addView(project);
        new AlertDialog.Builder(this).setTitle("Classer la fiche").setView(l).setPositiveButton("Classer",(d,w)->{put(n,"space",space.getSelectedItem().toString());put(n,"project",project.getText().toString().trim());put(n,"inbox",false);if(n.optString("status").equals("À classer"))put(n,"status","En cours");put(n,"updated",System.currentTimeMillis());persist();edit(n);}).setNeutralButton("Remettre à classer",(d,w)->{put(n,"inbox",true);put(n,"status","À classer");persist();edit(n);}).setNegativeButton("Annuler",null).show();
    }
    void setStatus(JSONObject n){String[] choices={"À classer","En cours","Résolu","À revoir","Terminé"};new AlertDialog.Builder(this).setTitle("État de la fiche").setItems(choices,(d,w)->{saveEditor();put(n,"status",choices[w]);put(n,"inbox",w==0);persist();edit(n);}).show();}
    void manageTemplates(){JSONArray ts=db.optJSONArray("templates");if(ts.length()==0){templates();return;}String[] names=new String[ts.length()];for(int i=0;i<names.length;i++)names[i]=ts.optJSONObject(i).optString("name");new AlertDialog.Builder(this).setTitle("Mes modèles").setItems(names,(d,w)->new AlertDialog.Builder(this).setTitle(names[w]).setItems(new String[]{"Renommer","Supprimer"},(dialog,index)->{if(index==0){EditText value=new EditText(this);value.setText(names[w]);new AlertDialog.Builder(this).setTitle("Nom du modèle").setView(value).setPositiveButton("Enregistrer",(x,y)->{String name=value.getText().toString().trim();if(!name.isEmpty()){put(ts.optJSONObject(w),"name",name);persist();}}).show();}else new AlertDialog.Builder(this).setTitle("Supprimer le modèle ?").setMessage("Les fiches créées à partir de ce modèle sont conservées.").setPositiveButton("Supprimer",(x,y)->{ts.remove(w);persist();}).setNegativeButton("Annuler",null).show();}).show()).show();}
    void savedSearches(){JSONArray searches=db.optJSONArray("searches");if(searches==null){searches=new JSONArray();put(db,"searches",searches);}final JSONArray values=searches;String[] names=new String[values.length()];for(int i=0;i<names.length;i++)names[i]=values.optJSONObject(i).optString("name");new AlertDialog.Builder(this).setTitle("Recherches enregistrées").setItems(names,(d,w)->{JSONObject q=values.optJSONObject(w);query=q.optString("query");filter=q.optString("tag");projectFilter=q.optString("project");statusFilter=q.optString("status");currentSpace=q.optString("space",currentSpace);globalSearch=q.optBoolean("global");screen="Fiches";trash=false;home();}).setPositiveButton("Enregistrer la recherche actuelle",(d,w)->{EditText name=new EditText(this);name.setHint("Nom de la recherche");new AlertDialog.Builder(this).setTitle("Enregistrer").setView(name).setPositiveButton("Enregistrer",(x,y)->{if(name.getText().toString().trim().isEmpty())return;JSONObject q=new JSONObject();put(q,"name",name.getText().toString());put(q,"query",query);put(q,"tag",filter);put(q,"project",projectFilter);put(q,"status",statusFilter);put(q,"space",currentSpace);put(q,"global",globalSearch);values.put(q);persist();}).show();}).show();}
    void renderBlocks(LinearLayout content,JSONObject n){
        JSONArray blocks=n.optJSONArray("blocks");if(blocks==null)return;if(blocks.length()>0)section(content,"DOCUMENT");
        for(int i=0;i<blocks.length();i++){
            JSONObject block=blocks.optJSONObject(i);String id=block.optString("id"),type=block.optString("type");LinearLayout top=row();content.addView(top);TextView name=text(type,13,muted());top.addView(name,new LinearLayout.LayoutParams(0,-2,1));Button menu=button(top,"•••",()->blockMenu(n,block));menu.setLayoutParams(new LinearLayout.LayoutParams(dp(48),dp(48)));
            if(type.equals("Image")||type.equals("Fichier")){String fileId=block.optString("fileId");JSONArray files=n.optJSONArray("files");for(int j=0;j<files.length();j++){JSONObject f=files.optJSONObject(j);if(!f.optString("id").equals(fileId))continue;if(type.equals("Image")){android.graphics.BitmapFactory.Options o=new android.graphics.BitmapFactory.Options();o.inJustDecodeBounds=true;String path=new File(getFilesDir(),"attachments/"+fileId).toString();android.graphics.BitmapFactory.decodeFile(path,o);o.inSampleSize=1;while(Math.max(o.outWidth,o.outHeight)/o.inSampleSize>800)o.inSampleSize*=2;o.inJustDecodeBounds=false;android.graphics.Bitmap bitmap=android.graphics.BitmapFactory.decodeFile(path,o);if(bitmap!=null){ImageView image=new ImageView(this);image.setImageBitmap(bitmap);image.setAdjustViewBounds(true);image.setMaxHeight(dp(240));content.addView(image,new LinearLayout.LayoutParams(-1,-2));image.setOnClickListener(v->openAttachment(f));}}button(content,f.optString("name"),()->openAttachment(f));}continue;}
            if(type.equals("Question / réponse")){String[] parts=block.optString("text").split("\\n---\\n",2);EditText question=input(content,"Question",parts[0],true);EditText answer=input(content,"Réponse",parts.length>1?parts[1]:"",true);blockEditors.put(id+".question",question);blockEditors.put(id+".answer",answer);continue;}
            EditText value=input(content,type.equals("Tableau")?"Colonnes séparées par |, une ligne par rangée":type,block.optString("text"),true);blockEditors.put(id,value);if(type.equals("Tableau")){value.setVisibility(View.GONE);tablePreview(content,block.optString("text"));button(content,"Modifier les cellules",()->editTable(value,n));}if(type.equals("Titre")){value.setTextSize(fontSize+5);value.setTypeface(null,1);}if(type.equals("Code")||type.equals("Commande")||type.equals("Résultat")){value.setTypeface(android.graphics.Typeface.MONOSPACE);value.setTextSize(fontSize-1);}if(type.equals("Code")||type.equals("Commande"))button(content,"Copier",()->{android.content.ClipboardManager clipboard=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);clipboard.setPrimaryClip(ClipData.newPlainText(type,value.getText().toString()));message("Copié.");});if(type.equals("Tâche")){CheckBox checked=new CheckBox(this);checked.setText("Terminée");checked.setChecked(block.optBoolean("done"));content.addView(checked);checked.setOnCheckedChangeListener((view,on)->{put(block,"done",on);saveEditor();persist();});}
        }
    }
    void addBlock(){String[] kinds={"Texte","Titre","Liste","Code","Citation","Tableau","Tâche","Lien","Commande","Résultat","Question / réponse","Image","Fichier","Photo","Note vocale"};new AlertDialog.Builder(this).setTitle("Ajouter un bloc").setItems(kinds,(d,w)->{saveEditor();String kind=kinds[w];if(kind.equals("Image")||kind.equals("Fichier")){pendingBlockType=kind;pick(ATTACH,kind.equals("Image")?"image/*":"*/*");return;}if(kind.equals("Photo")){camera();return;}if(kind.equals("Note vocale")){voice();return;}JSONObject block=new JSONObject();put(block,"id",UUID.randomUUID().toString());put(block,"type",kind);put(block,"text","");JSONArray blocks=editing.optJSONArray("blocks");if(blocks==null){blocks=new JSONArray();put(editing,"blocks",blocks);}blocks.put(block);persist();edit(editing);}).show();}
    String pendingBlockType="";
    void blockMenu(JSONObject n,JSONObject block){new AlertDialog.Builder(this).setTitle("Options du bloc").setItems(new String[]{"Monter","Descendre","Supprimer"},(d,w)->{saveEditor();JSONArray blocks=n.optJSONArray("blocks");List<JSONObject> ordered=new ArrayList<>();int index=-1;for(int j=0;j<blocks.length();j++){JSONObject b=blocks.optJSONObject(j);ordered.add(b);if(b==block)index=j;}if(index<0)return;if(w==2){new AlertDialog.Builder(this).setTitle("Supprimer ce bloc ?").setPositiveButton("Supprimer",(x,y)->{blocks.remove(ordered.indexOf(block));persist();editing=null;edit(n);}).setNegativeButton("Annuler",null).show();return;}int target=w==0?index-1:index+1;if(target<0||target>=ordered.size())return;Collections.swap(ordered,index,target);JSONArray next=new JSONArray();for(JSONObject b:ordered)next.put(b);put(n,"blocks",next);persist();editing=null;edit(n);}).show();}
    void purge(JSONObject n){new AlertDialog.Builder(this).setTitle("Supprimer définitivement ?").setMessage("Cette fiche et ses versions seront supprimées. Les fichiers utilisés par d’autres fiches seront conservés.").setPositiveButton("Supprimer",(d,w)->{saveEditor();for(int i=0;i<notes.length();i++)if(notes.optJSONObject(i)==n){notes.remove(i);break;}editing=null;ReminderReceiver.schedule(this,n.optString("id"),n.optString("title"),0);persist();garbageCollect();home();}).setNegativeButton("Annuler",null).show();}
    void garbageCollect(){Set<String> used=new HashSet<>();for(int i=0;i<notes.length();i++){JSONArray files=notes.optJSONObject(i).optJSONArray("files");for(int j=0;j<files.length();j++)used.add(files.optJSONObject(j).optString("id"));}for(int i=0;i<notes.length();i++){JSONArray versions=notes.optJSONObject(i).optJSONArray("versions");for(int j=0;j<versions.length();j++){JSONArray refs=versions.optJSONObject(j).optJSONArray("files");if(refs!=null)for(int k=0;k<refs.length();k++)used.add(refs.optJSONObject(k).optString("id"));}}File[] files=new File(getFilesDir(),"attachments").listFiles();if(files!=null)for(File f:files)if(!used.contains(f.getName()))f.delete();}
    void attachmentMenu(JSONObject n,JSONObject f){new AlertDialog.Builder(this).setTitle(f.optString("name")).setItems(new String[]{"Ouvrir","Remplacer dans cette fiche","Retirer de cette fiche","Annoter une image"},(d,w)->{if(w==3){saveEditor();startActivityForResult(new Intent(this,AnnotationActivity.class).putExtra("fileId",f.optString("id")),61);}else if(w==0)openAttachment(f);else if(w==1){replacingFile=f.optString("id");pick(ATTACH,"*/*");}else new AlertDialog.Builder(this).setTitle("Retirer ce fichier ?").setMessage("Les autres fiches qui l’utilisent sont conservées.").setPositiveButton("Retirer",(x,y)->{saveEditor();JSONArray files=n.optJSONArray("files");for(int i=0;i<files.length();i++)if(files.optJSONObject(i)==f){files.remove(i);break;}JSONArray blocks=n.optJSONArray("blocks");if(blocks!=null)for(int i=blocks.length()-1;i>=0;i--)if(blocks.optJSONObject(i).optString("fileId").equals(f.optString("id")))blocks.remove(i);persist();editing=null;edit(n);}).setNegativeButton("Annuler",null).show();}).show();}
    void fileLibrary(){LinearLayout contents=column();ScrollView scroll=new ScrollView(this);scroll.addView(contents);Set<String> shown=new HashSet<>();for(int i=0;i<notes.length();i++){JSONObject n=notes.optJSONObject(i);if(!n.optString("space","Études").equals(currentSpace))continue;JSONArray files=n.optJSONArray("files");for(int j=0;j<files.length();j++){JSONObject f=files.optJSONObject(j);if(!shown.add(f.optString("id")))continue;long size=new File(getFilesDir(),"attachments/"+f.optString("id")).length();button(contents,f.optString("name")+" · "+android.text.format.Formatter.formatShortFileSize(this,size),()->new AlertDialog.Builder(this).setTitle(f.optString("name")).setItems(new String[]{"Ouvrir","Voir la fiche","Renommer"},(d,w)->{if(w==0)openAttachment(f);else if(w==1)edit(n);else{EditText name=new EditText(this);name.setText(f.optString("name"));new AlertDialog.Builder(this).setTitle("Nom du fichier").setView(name).setPositiveButton("Enregistrer",(x,y)->{String value=name.getText().toString().trim();if(!value.isEmpty()){for(int a=0;a<notes.length();a++){JSONArray all=notes.optJSONObject(a).optJSONArray("files");for(int b=0;b<all.length();b++)if(all.optJSONObject(b).optString("id").equals(f.optString("id")))put(all.optJSONObject(b),"name",value);}persist();}}).show();}}).show());}}new AlertDialog.Builder(this).setTitle("Fichiers · "+currentSpace).setView(scroll).setPositiveButton("Fermer",null).show();}
    String markdown(JSONObject n){StringBuilder out=new StringBuilder("# "+n.optString("title")+"\n\n");out.append("Espace : ").append(n.optString("space")).append("\nProjet : ").append(n.optString("project")).append("\nÉtat : ").append(n.optString("status")).append("\nÉtiquettes : ").append(n.optString("tags")).append("\n\n").append(n.optString("body")).append("\n\n");JSONArray fields=n.optJSONArray("fields");for(int i=0;i<fields.length();i++){JSONObject f=fields.optJSONObject(i);out.append("## ").append(f.optString("name")).append("\n").append(f.optString("value")).append("\n\n");}JSONArray blocks=n.optJSONArray("blocks");if(blocks!=null)for(int i=0;i<blocks.length();i++){JSONObject b=blocks.optJSONObject(i);String type=b.optString("type"),text=b.optString("text");if(type.equals("Titre"))out.append("## ");if(type.equals("Code"))out.append("```\n");if(type.equals("Citation"))out.append("> ");if(type.equals("Tâche"))out.append(b.optBoolean("done")?"- [x] ":"- [ ] ");out.append(text).append('\n');if(type.equals("Code"))out.append("```\n");out.append('\n');}JSONArray files=n.optJSONArray("files");for(int i=0;i<files.length();i++){JSONObject f=files.optJSONObject(i);out.append("- [").append(f.optString("name").replace("]","\\]")).append("](../../attachments/").append(f.optString("id")).append(")\n");}return out.toString();}
    void exportPdf(JSONObject n){saveEditor();android.webkit.WebView view=new android.webkit.WebView(this);view.getSettings().setJavaScriptEnabled(false);view.setWebViewClient(new android.webkit.WebViewClient(){public void onPageFinished(android.webkit.WebView web,String url){android.print.PrintManager manager=(android.print.PrintManager)getSystemService(PRINT_SERVICE);manager.print("Mémoire — "+n.optString("title"),web.createPrintDocumentAdapter("Mémoire"),new android.print.PrintAttributes.Builder().setMediaSize(android.print.PrintAttributes.MediaSize.ISO_A4).build());}});view.loadDataWithBaseURL(null,"<html><meta charset='utf-8'><body style='font-family:sans-serif;padding:24px'><pre style='white-space:pre-wrap;font-family:sans-serif;line-height:1.5'>"+android.text.Html.escapeHtml(markdown(n))+"</pre></body></html>","text/html","UTF-8",null);}
    void exportMarkdown(){saveEditor();Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/zip").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"Memoire-documents.zip");startActivityForResult(i,50);}
    void backupOptions(){new AlertDialog.Builder(this).setTitle("Sauvegarde complète").setItems(new String[]{"ZIP standard","Sauvegarde chiffrée avec mot de passe"},(d,w)->{if(w==0){archivePassword=null;pendingExportEncrypted=false;exportData();}else password("Mot de passe de la sauvegarde",true,value->{archivePassword=value;pendingExportEncrypted=true;exportData();});}).show();}
    interface PasswordAction{void run(char[] value);}
    void password(String title,boolean confirm,PasswordAction action){LinearLayout l=column();EditText first=input(l,"Mot de passe","",false);first.setInputType(129);EditText second=confirm?input(l,"Confirmer le mot de passe","",false):null;if(second!=null)second.setInputType(129);AlertDialog dialog=new AlertDialog.Builder(this).setTitle(title).setMessage(confirm?"Conserve ce mot de passe : il ne peut pas être récupéré.":"Saisis le mot de passe utilisé lors de l’export.").setView(l).setPositiveButton("Continuer",null).setNegativeButton("Annuler",null).create();dialog.setOnShowListener(v->dialog.getButton(-1).setOnClickListener(button->{String value=first.getText().toString();if(value.length()<8){first.setError("Au moins 8 caractères");return;}if(second!=null&&!value.equals(second.getText().toString())){second.setError("Les mots de passe diffèrent");return;}dialog.dismiss();action.run(value.toCharArray());}));dialog.show();}
    void camera(){if(editing==null)return;saveEditor();String id=UUID.randomUUID().toString();File dir=new File(getFilesDir(),"attachments");dir.mkdirs();try{new File(dir,id).createNewFile();pendingMedia=new JSONObject();put(pendingMedia,"id",id);put(pendingMedia,"name","Photo-"+System.currentTimeMillis()+".jpg");Uri uri=new Uri.Builder().scheme("content").authority("bf.memoire.files").appendPath(id).appendPath(pendingMedia.optString("name")).build();Intent capture=new Intent(android.provider.MediaStore.ACTION_IMAGE_CAPTURE).putExtra(android.provider.MediaStore.EXTRA_OUTPUT,uri).addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_READ_URI_PERMISSION);capture.setClipData(ClipData.newRawUri("Photo",uri));setRequestedOrientation(android.content.pm.ActivityInfo.SCREEN_ORIENTATION_LOCKED);startActivityForResult(capture,60);}catch(Exception e){message("Impossible d’ouvrir l’appareil photo.");pendingMedia=null;}}
    void finishCamera(int result){setRequestedOrientation(android.content.pm.ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);if(pendingMedia==null)return;File file=new File(getFilesDir(),"attachments/"+pendingMedia.optString("id"));if(result==RESULT_OK&&file.length()>0&&editing!=null){addAttachmentRecord(editing,pendingMedia,"Image");persist();edit(editing);}else file.delete();pendingMedia=null;}
    android.media.MediaRecorder recorder;
    JSONObject voiceOwner,voiceFile;
    void voice(){if(editing==null)return;if(checkSelfPermission(android.Manifest.permission.RECORD_AUDIO)!=android.content.pm.PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.RECORD_AUDIO},81);message("Autorise le microphone, puis choisis à nouveau Note vocale.");return;}saveEditor();try{String id=UUID.randomUUID().toString();File dir=new File(getFilesDir(),"attachments");dir.mkdirs();voiceOwner=editing;voiceFile=new JSONObject();put(voiceFile,"id",id);put(voiceFile,"name","Note-vocale-"+System.currentTimeMillis()+".m4a");recorder=new android.media.MediaRecorder();recorder.setAudioSource(android.media.MediaRecorder.AudioSource.MIC);recorder.setOutputFormat(android.media.MediaRecorder.OutputFormat.MPEG_4);recorder.setAudioEncoder(android.media.MediaRecorder.AudioEncoder.AAC);recorder.setOutputFile(new File(dir,id).toString());recorder.prepare();recorder.start();new AlertDialog.Builder(this).setTitle("Enregistrement en cours").setMessage("Le son est enregistré uniquement sur ce téléphone. Quitter l’application arrête l’enregistrement.").setCancelable(false).setPositiveButton("Arrêter et conserver",(d,w)->stopVoice(true)).setNegativeButton("Annuler",(d,w)->stopVoice(false)).show();}catch(Exception e){stopVoice(false);message("Enregistrement impossible : "+e.getMessage());}}
    void stopVoice(boolean keep){if(recorder==null)return;try{recorder.stop();}catch(Exception e){keep=false;}recorder.release();recorder=null;if(voiceFile!=null){File file=new File(getFilesDir(),"attachments/"+voiceFile.optString("id"));if(keep&&file.length()>0){addAttachmentRecord(voiceOwner,voiceFile,"Fichier");persist();JSONObject owner=voiceOwner;runOnUiThread(()->edit(owner));}else file.delete();}voiceOwner=null;voiceFile=null;}
    void addAttachmentRecord(JSONObject owner,JSONObject file,String blockType){JSONArray refs=owner.optJSONArray("files");boolean exists=false;for(int i=0;i<refs.length();i++)if(refs.optJSONObject(i).optString("id").equals(file.optString("id")))exists=true;if(!exists)refs.put(file);if(!blockType.isEmpty()){JSONArray blocks=owner.optJSONArray("blocks");if(blocks==null){blocks=new JSONArray();put(owner,"blocks",blocks);}JSONObject block=new JSONObject();put(block,"id",UUID.randomUUID().toString());put(block,"type",blockType);put(block,"fileId",file.optString("id"));blocks.put(block);}}
    void seedTemplates(){if(db.optBoolean("seededModels"))return;String[][] models={{"Problème et solution","Symptômes","Contexte","Essais","Solution","Vérification"},{"Cours","Notions","Exemples","Exercices","À revoir"},{"Projet","Objectif","Prérequis","Étapes","Décisions","Résultat"},{"Procédure","Pré requis","Commandes","Résultat attendu","Erreurs fréquentes"},{"Ressource","Source","Résumé","Utilité"},{"Idée","Description","Intérêt","Prochaine action"}};JSONArray templates=db.optJSONArray("templates");for(String[] model:models){JSONObject template=new JSONObject();put(template,"name",model[0]);JSONArray fields=new JSONArray();for(int i=1;i<model.length;i++){JSONObject field=new JSONObject();put(field,"id",UUID.randomUUID().toString());put(field,"name",model[i]);put(field,"type","Texte long");put(field,"value","");fields.put(field);}put(template,"fields",fields);templates.put(template);}put(db,"seededModels",true);}
    void projects(){Set<String> names=new TreeSet<>();for(int i=0;i<notes.length();i++){JSONObject n=notes.optJSONObject(i);if(n.optString("space").equals(currentSpace)&&!n.optBoolean("deleted")&&!n.optString("project").isEmpty())names.add(n.optString("project"));}String[] projects=names.toArray(new String[0]);new AlertDialog.Builder(this).setTitle("Projets et matières · "+currentSpace).setItems(projects,(d,w)->{projectFilter=projects[w];screen="Fiches";inbox=false;archive=false;home();}).setNeutralButton("Tout afficher",(d,w)->{projectFilter="";screen="Fiches";home();}).show();}
    void revision(){List<JSONObject> cards=new ArrayList<>();for(int i=0;i<notes.length();i++){JSONObject n=notes.optJSONObject(i);if(n.optBoolean("deleted")||n.optBoolean("archived")||!n.optString("space").equals(currentSpace))continue;JSONArray blocks=n.optJSONArray("blocks");if(blocks!=null)for(int j=0;j<blocks.length();j++){JSONObject b=blocks.optJSONObject(j);if(b.optString("type").equals("Question / réponse")&&b.optLong("reviewAt")<=System.currentTimeMillis()){JSONObject item=new JSONObject();put(item,"note",n);put(item,"block",b);cards.add(item);}}}if(cards.isEmpty()){message("Aucune question à réviser. Ajoute un bloc Question / réponse dans un cours.");return;}reviewCard(cards,0);}
    void reviewCard(List<JSONObject> cards,int index){if(index>=cards.size()){message("Session de révision terminée.");home();return;}JSONObject item=cards.get(index),n=item.optJSONObject("note"),block=item.optJSONObject("block");String[] parts=block.optString("text").split("\\n---\\n",2);LinearLayout l=column();l.addView(text(parts[0],fontSize+2,ink()));TextView answer=text(parts.length>1?parts[1]:"Réponse non renseignée",fontSize,muted());answer.setPadding(0,dp(20),0,0);answer.setVisibility(View.GONE);l.addView(answer);button(l,"Afficher la réponse",()->answer.setVisibility(View.VISIBLE));new AlertDialog.Builder(this).setTitle((index+1)+" / "+cards.size()+" · "+n.optString("title")).setView(l).setPositiveButton("Compris",(d,w)->{put(block,"reviewAt",System.currentTimeMillis()+7L*86400000);persist();reviewCard(cards,index+1);}).setNeutralButton("À revoir demain",(d,w)->{put(block,"reviewAt",System.currentTimeMillis()+86400000);put(n,"status","À revoir");persist();reviewCard(cards,index+1);}).setNegativeButton("Quitter",null).show();}
    void editTable(EditText source,JSONObject owner){
        String[] lines=source.getText().toString().split("\\n",-1);List<String[]> existing=new ArrayList<>();int columns=2;for(String line:lines){String[] cells=line.split("\\|",-1);existing.add(cells);columns=Math.max(columns,cells.length);}LinearLayout size=column();EditText rows=input(size,"Nombre de lignes",Integer.toString(Math.max(2,lines.length)),false);EditText cols=input(size,"Nombre de colonnes",Integer.toString(columns),false);rows.setInputType(2);cols.setInputType(2);
        new AlertDialog.Builder(this).setTitle("Dimensions du tableau").setView(size).setPositiveButton("Continuer",(d,w)->{int r,c;try{r=Integer.parseInt(rows.getText().toString());c=Integer.parseInt(cols.getText().toString());}catch(Exception e){message("Dimensions invalides");return;}if(r<1||r>30||c<1||c>10){message("De 1 à 30 lignes et de 1 à 10 colonnes.");return;}HorizontalScrollView horizontal=new HorizontalScrollView(this);android.widget.TableLayout table=new android.widget.TableLayout(this);horizontal.addView(table);List<List<EditText>> editors=new ArrayList<>();for(int y=0;y<r;y++){TableRow row=new TableRow(this);List<EditText> line=new ArrayList<>();for(int x=0;x<c;x++){EditText cell=new EditText(this);cell.setText(y<existing.size()&&x<existing.get(y).length?existing.get(y)[x]:"");cell.setHint((y+1)+","+(x+1));cell.setTextSize(fontSize);cell.setPadding(dp(8),dp(8),dp(8),dp(8));row.addView(cell,new TableRow.LayoutParams(dp(120),-2));line.add(cell);}table.addView(row);editors.add(line);}ScrollView vertical=new ScrollView(this);vertical.addView(horizontal);new AlertDialog.Builder(this).setTitle("Modifier le tableau").setView(vertical).setPositiveButton("Enregistrer",(dialog,index)->{StringBuilder text=new StringBuilder();for(int y=0;y<editors.size();y++){if(y>0)text.append('\n');List<EditText> line=editors.get(y);for(int x=0;x<line.size();x++){if(x>0)text.append('|');text.append(line.get(x).getText().toString().replace('|','/').replace('\n',' '));}}source.setText(text);saveEditor();edit(owner);}).setNegativeButton("Annuler",null).show();}).setNegativeButton("Annuler",null).show();
    }
    void tablePreview(LinearLayout parent,String text){HorizontalScrollView scroll=new HorizontalScrollView(this);TableLayout table=new TableLayout(this);scroll.addView(table);String[] lines=text.split("\\n",-1);for(int y=0;y<Math.min(lines.length,30);y++){TableRow row=new TableRow(this);String[] cells=lines[y].split("\\|",-1);for(int x=0;x<Math.min(cells.length,10);x++){TextView cell=text(cells[x].isEmpty()?"—":cells[x],fontSize,ink());cell.setPadding(dp(10),dp(10),dp(10),dp(10));android.graphics.drawable.GradientDrawable border=shape(surface(),0);border.setStroke(dp(1),muted());cell.setBackground(border);row.addView(cell,new TableRow.LayoutParams(dp(120),-2));}table.addView(row);}parent.addView(scroll);}
    void deleteTree(File f){File[] children=f.listFiles();if(children!=null)for(File c:children)deleteTree(c);f.delete();}
    @Override protected void onSaveInstanceState(Bundle out){saveEditor();out.putString("screen",screen);out.putString("query",query);out.putBoolean("unlocked",unlocked);out.putBoolean("encryptedExport",pendingExportEncrypted);out.putString("pendingBlockType",pendingBlockType);out.putString("replace",replacingFile);if(editing!=null)out.putString("editId",editing.optString("id"));if(pendingMedia!=null)out.putString("media",pendingMedia.toString());super.onSaveInstanceState(out);}
    @Override protected void onPause(){if(recorder!=null)stopVoice(true);saveEditor();super.onPause();}
    @Override public void onBackPressed(){if(editing!=null||trash){trash=false;home();}else super.onBackPressed();}
}
